aa: rand-m9-mstd0.5-inc1
amp: true
batch_size: 64
cfg: ./experiments_configs/classification/supernet-T.yaml
change_qkv: true
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
crossover_num: 25
cutmix: 1.0
cutmix_minmax: null
data_path: ./data/evol_cifar100
data_set: CIFAR100
decay_epochs: 30
decay_rate: 0.1
device: cuda
dist_backend: nccl
dist_eval: true
dist_url: env://
distributed: true
drop: 0.0
drop_block: null
drop_path: 0.1
epochs: 30
eval: false
gp: true
gpu: 0
inat_category: name
input_size: 224
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
m_prob: 0.2
max_epochs: 20
max_relative_position: 14
min_lr: 1.0e-05
min_param_limits: 0.0
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
mutation_num: 25
no_abs_pos: false
no_prefetcher: false
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ''
param_limits: 5.560792
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
population_num: 50
post_norm: false
rank: 0
recount: 1
relative_position: true
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: ./output_change/checkpoint.pth
rpe_type: bias
s_prob: 0.4
scale: false
sched: cosine
seed: 0
select_num: 10
smoothing: 0.1
start_epoch: 0
teacher_model: ''
train_interpolation: bicubic
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
world_size: 1
