MODEL:
  TYPE: swin_minivit_distill
  NAME: swin_base_patch4_window7_224_minivit
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
MINIVIT:
  SEPARATE_LAYERNUM_LIST: [1, 1, 9, 1]