aa: rand-m9-mstd0.5-inc1
amp: true
batch_size: 16
cfg: ./experiments_configs/supernet-swinir/supernet-T.yaml
change_qkv: false
clip_grad: null
color_jitter: 0.4
cutmix: 1.0
cutmix_minmax: null
data_path: ./data/imagenet/
data_set: IMNET
decay_epochs: 50
decay_rate: 0.5
device: cuda:0
dist_eval: false
dist_url: env://
distributed: false
drop: 0.0
drop_block: null
drop_path: 0.1
epochs: 300
eval: false
gp: false
inat_category: name
input_size: 64
lr: 0.0002
max_relative_position: 14
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
mode: super
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.999
no_abs_pos: false
num_workers: 8
opt: adam
opt_doc: ./experiments_configs/supernet-swinir/train_swinir_sr_lightweight.json
output_dir: ./output_swinir_final_split
patch_size: 8
pin_mem: true
platform: pai
post_norm: false
recount: 1
relative_position: false
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: ''
rpe_type: bias
sched: step
seed: 0
smoothing: 0.1
start_epoch: 0
teacher_model: ''
train_interpolation: bicubic
warmup_epochs: 0
warmup_lr: 0
weight_decay: 0
world_size: 1
